#! /usr/bin/env python
# encoding: utf-8
# mittorn, 2018

def options(opt):
	pass

def configure(conf):
	pass

def build(bld):
	bld.shlib(
		source   = ['r_context.c', 'r_image.c', 'r_d3d.c', 'r_main.c', 'r_draw.c', 'r_surf.c'],
		target   = 'ref_dx2',
		defines  = 'REF_DLL',
		use      = 'engine_includes sdk_includes werror public USER32 DDRAW',
		install_path = bld.env.LIBDIR
	)
