#! /usr/bin/env python
# encoding: utf-8
# a1batross, mittorn, 2018

def options(opt):
	# TODO: any options for mdldec?
	grp = opt.get_option_group('Utilities options')

	grp.add_option('--disable-utils-mdldec', action = 'store_true', dest = 'DISABLE_UTILS_MDLDEC', default = False,
                help = 'disable studio model decompiler utility [default: %(default)s]')

def configure(conf):
	conf.env.DISABLE_UTILS_MDLDEC = conf.options.DISABLE_UTILS_MDLDEC

def build(bld):
	if bld.env.DISABLE_UTILS_MDLDEC:
		return

	bld.program(source   = bld.path.ant_glob('*.c'),
		target   = 'mdldec',
		includes = '.',
		use      = 'engine_includes public M werror',
		install_path = bld.env.BINDIR,
		subsystem = bld.env.CONSOLE_SUBSYSTEM
	)

	bld.install_files(bld.env.SHAREDIR, 'res/activities.txt')
