#! /usr/bin/env python
# encoding: utf-8

top = '.'

def options(opt):
	pass

def configure(conf):
	pass

def build(bld):
	bld.stlib(source = bld.path.ant_glob('*.c'),
		target = 'ref_common',
		includes = '.',
		export_includes = '.',
		use = 'engine_includes public werror',
		subsystem = bld.env.MSVC_SUBSYSTEM
	)
