#version 460

layout(local_size_x = 16, local_size_y = 8, local_size_z = 1) in;

layout(set = 0, binding = 0, rgba8) uniform image2D source;
layout(set = 0, binding = 1, rgba8) uniform image2D dest;

void main() {
	ivec2 res = ivec2(imageSize(source));
	ivec2 pix = ivec2(gl_GlobalInvocationID);

	vec3 colour = vec3(0.);

	if (all(lessThan(pix, res)))
		colour = imageLoad(source, pix).rgb;

	imageStore(dest, pix, vec4(colour, 1.));
}
