#! /usr/bin/env python
# encoding: utf-8

import os

def options(opt):
	pass

def configure(conf):
	conf.define('REF_DLL', 1)

def build(bld):
	source = bld.path.ant_glob( [ '*.c' ] )
	includes = [ '.' ]
	libs = [ 'engine_includes', 'sdk_includes' ]
	bld.env.LDFLAGS += ['-fPIC']
	bld.env.CFLAGS += ['-fPIC']
	bld.stlib(
		source    = source,
		target    = 'gl2_shim',
		features  = 'c',
		includes  = includes,
		use       = libs,
		subsystem = bld.env.MSVC_SUBSYSTEM
	)
