#! /usr/bin/env python
# encoding: utf-8
# mittorn, 2018

def options(opt):
	pass

def configure(conf):
	pass

def build(bld):
	bld.shlib(
		source   = 'r_context.c',
		target   = 'ref_null',
		defines  = 'REF_DLL',
		use      = 'engine_includes sdk_includes werror',
		install_path = bld.env.LIBDIR
	)
