#! /usr/bin/env python
# encoding: utf-8
# mittorn, 2018

from waflib import Logs
import os

top = '.'

def options(opt):
	# stub
	return

def configure(conf):
	# stub
	return

def build(bld):
	source = bld.path.ant_glob(['*.c'])
	libs = []
	includes = [ '.', '../common', '../engine' ]

	bld.stlib(
		source   = source,
		target   = 'public',
		features = 'c',
		includes = includes,
		use      = libs,
		subsystem = bld.env.MSVC_SUBSYSTEM
	)
