#! /usr/bin/env python
# encoding: utf-8
# mittorn, 2018

from waflib import Logs
import os

top = '.'

def options(opt):
	# stub
	return

def configure(conf):
	# stub
	return

def build(bld):
	bld(name = 'sdk_includes', export_includes = '. ../common ../pm_shared ../engine')
	bld.stlib(source   = bld.path.ant_glob('*.c'),
		target   = 'public',
		features = 'c',
		use      = 'sdk_includes',
		subsystem = bld.env.MSVC_SUBSYSTEM)
