#!/usr/bin/env python
# encoding: utf-8
# a1batross, 2019

def options(opt):
	# opt.load('java')
	opt.load('android')
	return

def configure(conf):
	conf.load('android')
	conf.env.D8_DEBUG = conf.options.BUILD_TYPE != 'release'
	# conf.load('java')
	return

def build(bld):
	bld(features = 'android javac',
		srcdir = 'src',
		compat = '1.6',
		name = 'xashdroid',
		jni = 'lib',
		keystore = bld.path.parent.find_node('debug.keystore'),
		debug = bld.env.D8_DEBUG,
		target_api = 28)
	return
