#pragma once

#define MAX_SCENE_STACK 2
#define MAX_SCENE_ENTITIES 2048

#define MAX_TEXTURES	4096

// TODO count these properly
#define MAX_BUFFER_VERTICES (1 * 1024 * 1024)
#define MAX_BUFFER_INDICES (MAX_BUFFER_VERTICES * 3)

#define MAX_VISIBLE_DLIGHTS 15
#define MAX_VISIBLE_SURFACE_LIGHTS 15
