#! /usr/bin/env python
# encoding: utf-8
# mittorn, 2018

from waflib import Logs
import os

top = '.'

def options(opt):
	grp = opt.add_option_group('ref_vk options')
	# stub
	return

def configure(conf):
	# check for dedicated server build
	if conf.options.DEDICATED:
		return
	conf.define('REF_DLL',1)
	#conf.define_cond('SUPPORT_BSP2_FORMAT', conf.options.SUPPORT_BSP2_FORMAT)

def build(bld):
	libs = [ 'public', 'M']

	source = bld.path.ant_glob(['*.c'])

	includes = ['.',
		'../engine',
		'../engine/common',
		'../engine/server',
		'../engine/client',
		'../public',
		'../common',
		'../pm_shared' ]


	bld.shlib(
		source   = source,
		target   = 'ref_vk',
		features = 'c',
		includes = includes,
		use      = libs,
		defines  = [], #['XASH_GL_STATIC'] if bld.env.GL_STATIC else [],
		install_path = bld.env.LIBDIR,
		subsystem = bld.env.MSVC_SUBSYSTEM
	)


