#! /usr/bin/env python
# encoding: utf-8
# mittorn, 2018

from waflib import Logs
import os

top = '.'

def options(opt):
	grp = opt.add_option_group('ref_vk options')

def configure(conf):
	# check for dedicated server build
	if conf.options.DEDICATED:
		return

	conf.load('glslc')
	conf.define('REF_DLL', 1)

	# conf.env.GLSLCFLAGS.append_unique(['-O'])

def build(bld):
	libs = [ 'public', 'M' ]

	source = bld.path.ant_glob(['*.c'])
	glsl_source = bld.path.ant_glob(['shaders/*.vert', 'shaders/*.frag'])

	includes = ['.',
		'../engine',
		'../engine/common',
		'../engine/server',
		'../engine/client',
		'../public',
		'../common',
		'../pm_shared' ]

	bld.shlib(
		source   = source,
		target   = 'ref_vk',
		features = 'c',
		includes = includes,
		use      = libs, #+ (['GL'] if bld.env.GL_STATIC else []),
		defines  = [], # ['XASH_GL_STATIC'] if bld.env.GL_STATIC else [],
		install_path = bld.env.LIBDIR,
		subsystem = bld.env.MSVC_SUBSYSTEM
	)

	bld(
		source = glsl_source,
		features = 'glsl',
		# includes = 'shaders/', # write your includes here
		# defines = 'TEST', # write your C preprocessor defines here
		install_path = '${LIBDIR}/valve' # TEMPORARY!!!!
	)

