#! /usr/bin/env python
# encoding: utf-8

import os

def options(opt):
	pass

def configure(conf):
	conf.define('REF_DLL', 1)

def build(bld):
	bld.env.CFLAGS_cstlib.remove('-fno-PIC')
	bld.env.CFLAGS += ['-fPIC']
	bld.stlib(source = bld.path.ant_glob('*.c'),
		target = 'vgl_shim',
		use = 'engine_includes sdk_includes werror',
		includes = '.')
