#!/usr/bin/env python
# encoding: utf-8

from waflib import Logs  # FIXED TYPO: "waflib", not "waftib"
import os

top = '.' 

def options(opt):
    # Vulkan options
    grp = opt.add_option_group('ref_vk options')
    grp.add_option('--enable-vulkan', action='store_true', dest='VULKAN', default=False,
        help='enable Vulkan renderer [default: %(default)s]')

def configure(conf):
    # Check Vulkan dependencies
    if conf.options.VULKAN:
        if not conf.check(lib='vulkan-1', msg='Checking for Vulkan library'):
            conf.fatal("Vulkan library not found!")
        if not conf.check_header('vulkan/vulkan.h', msg='Checking for Vulkan headers'):
            conf.fatal("Vulkan headers missing!")
        conf.env.VULKAN = True

    # Android-specific (if needed)
    if conf.env.DEST_OS2 == 'android':
        conf.check_cc(lib='log')

def build(bld):
    # Vulkan renderer target
    if not bld.env.VULKAN:
        return

    libs = ['engine_includes', 'werror', 'public', 'M']
    source = bld.path.ant_glob(['*.c', 'vk_shim/*.c'])  # Adjust to match your source files
    includes = '.' 

    bld.shlib(
        source=source,
        target='ref_vk',
        includes=includes,
        use=libs + ['vulkan-1'],
        defines=['XASH_VULKAN=1', 'REF_DLL=1'],
        install_path=bld.env.LIBDIR
    )
