#! /usr/bin/env python
# encoding: utf-8
# mittorn, 2018

from waflib import Logs
import os

top = '.'

def options(opt):
	return

def configure(conf):
	return

def build(bld):
	libs = [ 'engine_includes', 'werror' ]
	# on PSVita do not link any libraries that are already in the main executable, but add the includes target
	if bld.env.DEST_OS == 'psvita':
		libs += [ 'sdk_includes' ]
	else:
		libs += [ 'public', 'M' ]

	bld.shlib(source   = bld.path.ant_glob('*.c'),
		target   = 'ref_soft',
		includes = '.',
		defines  = 'REF_DLL=1',
		use      = libs,
		install_path = bld.env.LIBDIR
	)
